#load_data.sql
#by Joe Hahn
#joe.hahn@oracle.come
#July 19, 2023

#this loads csv file from Object Store into mysql database table

#drop pre-existing database;
drop database if exists Chicago;
create database Chicago;
CALL sys.heatwave_load(JSON_ARRAY('Chicago'), NULL);
use Chicago;

#set dataload parameters, being sure to get fresh PAR to csv file in ObjStore, and update the "par" setting below;
SET @db_list = '["Chicago"]';
SET @dl_tables = 
    '[{
        "db_name": "Chicago",
        "tables": [{
            "table_name": "crimes_ext",
            "dialect": {"format": "csv", "skip_rows": 1, "field_delimiter": ",", "record_delimiter": "\\n", "is_strict_mode": false},
            "file": [{"par": "https://objectstorage.us-ashburn-1.oraclecloud.com/p/ECiUvLjZXdvnX7UPpWe7F9v2CTB17ceRpZP7_j14n6i73YNeZjfKfZ-0q9SOnubN/n/orasenatdpltintegration03/b/JoeHahnBucket/o/chicago/crimes.csv"}]
        }]
    }]';
SET @options = JSON_OBJECT('mode', 'dryrun',  'policy', 'disable_unsupported_columns',  'external_tables', CAST(@dl_tables AS JSON));

#generate script that will autogenerate sql code that will load data into external mysql table
CALL sys.heatwave_load(@db_list, @options);

#execute script generated by the above, this outputs sql code that will create external table;
SELECT log->>"$.sql" AS "Load Script" FROM sys.heatwave_autopilot_report WHERE type = "sql" ORDER BY id;

#paste sql auto-generated by the above here, with col_1 replaced by ID, col_2 > Case_Number etc;
#also update "par" in the below
CREATE TABLE `Chicago`.`crimes_ext`( 
    `ID` int unsigned NOT NULL, 
    `Case_Number` varchar(9) COMMENT 'RAPID_COLUMN=ENCODING=VARLEN', 
    `Date` varchar(22) NOT NULL COMMENT 'RAPID_COLUMN=ENCODING=VARLEN', 
    `Block` varchar(38) NOT NULL COMMENT 'RAPID_COLUMN=ENCODING=VARLEN', 
    `IUCR` varchar(4) NOT NULL COMMENT 'RAPID_COLUMN=ENCODING=VARLEN', 
    `Primary_Type` varchar(33) NOT NULL COMMENT 'RAPID_COLUMN=ENCODING=VARLEN', 
    `Description` varchar(60) NOT NULL COMMENT 'RAPID_COLUMN=ENCODING=VARLEN', 
    `Location_Description` varchar(53) COMMENT 'RAPID_COLUMN=ENCODING=VARLEN', 
    `Arrest` varchar(5) NOT NULL COMMENT 'RAPID_COLUMN=ENCODING=VARLEN', 
    `Domestic` varchar(5) NOT NULL COMMENT 'RAPID_COLUMN=ENCODING=VARLEN', 
    `Beat` smallint unsigned NOT NULL, 
    `District` smallint unsigned, 
    `Ward` tinyint unsigned, 
    `Community_Area` tinyint unsigned, 
    `FBI_Code` varchar(3) NOT NULL COMMENT 'RAPID_COLUMN=ENCODING=VARLEN', 
    `X_Coordinate` int unsigned, 
    `Y_Coordinate` int unsigned, 
    `Year` year NOT NULL, 
    `Updated_On` varchar(22) NOT NULL COMMENT 'RAPID_COLUMN=ENCODING=VARLEN', 
    `Latitude` decimal(11,9), 
    `Longitude` decimal(11,9), 
    `Location` varchar(29) COMMENT 'RAPID_COLUMN=ENCODING=VARLEN') 
    ENGINE=lakehouse 
    SECONDARY_ENGINE=RAPID ENGINE_ATTRIBUTE='{"file": [{"par": "https://objectstorage.us-ashburn-1.oraclecloud.com/p/ECiUvLjZXdvnX7UPpWe7F9v2CTB17ceRpZP7_j14n6i73YNeZjfKfZ-0q9SOnubN/n/orasenatdpltintegration03/b/JoeHahnBucket/o/chicago/crimes.csv"}], "dialect": {"format": "csv", "skip_rows": 1, "is_strict_mode": false, "field_delimiter": ",", "record_delimiter": "\\n"}}';
ALTER TABLE crimes_ext SECONDARY_LOAD;

#derive internal table from external table
drop table if exists crimes;
create table crimes as select * from crimes_ext;
alter table crimes add column `ID_key` int(10) unsigned primary KEY AUTO_INCREMENT;

#drop external table that cannot be loaded into heatwave because that requires a primary key, and you cant use primary keys on external data. or so I think
drop table crimes_ext;

#confirm the above
select * from crimes limit 5;
select count(*) from crimes;
describe crimes;


